### ISSUE TITLE
Modales no funcionan

### ISSUE THREAD

**Issue by Angerback** [FeloVilches/Webforge-Express#12]
Los modales que usabamos también en angular en el proyecto rails no funcionan acá. Por favor revisar.

**Comment by Angerback** [comment]
Esto ocurre en la rama grupo 3 al hacer click en el icono del ojo en la lista de usuarios

**Comment by FeloVilches** [comment]
Una pregunta, los modales funcionaban en el proyecto de Rails?

**Comment by FeloVilches** [comment]
Si, si funcionan (ya lo vi). El problema es que incluso si lo arreglo, nuestras vistas se perderian, porque dependen del "show" de usuario, en particular la vista para mostrar el historial.

Lo que podriamos hacer es sacrificar nuestra vista de show de usuario, y dejarla como modal, pero que al cliquear el boton de historial, cambie de vista a la nuestra, porque ustedes no implementaron la vista de "mostrar historial de calificaciones" o si?

Propongo eso (y podemos trabajar hasta despues de la hora fijada, con el fin de solucionar el problema)

**Comment by FeloVilches** [comment]
@Angerback El error era que faltaba incluir ```bootstrap.js```. Ahora corren los modales.

Sin embargo, como tenemos que mezclar las HU (lo que dije en el comentario anterior), igual me ofrezco yo para pasar sus vistas a la mia. Tendre cuidado de pasar los controladores y servicios tambien.

**Comment by FeloVilches** [comment]
A futuro deje la tarea de refactorizar el codigo para eliminar este problema y mejorar la implementacion.

Deje el issue que cree (y cierro este): https://github.com/FeloVilches/Webforge-Express/issues/13
