### ISSUE TITLE
¿se puede acceder a un usuario?

### ISSUE THREAD

**Issue by nelsonjerezv** [FeloVilches/Webforge-Express#21]
la duda es para obtener sus datos, gracias

**Comment by FeloVilches** [comment]
No se a que te refieres; si te refieres a obtener el JSON de cada usuario, tendria que ser desde el webservice (backend). Y si te refieres a obtenerlos en la GUI, si hay una vista que muestra algunos datos, pero no se si son todos los que necesitas.

**Comment by nelsonjerezv** [comment]
ahi vine a darme cuenta, hay que tener corriendo el original y express, gracias de todas formas
