### ISSUE TITLE
No puedo ver el Home ni nada 

### ISSUE THREAD

**Issue by fbnr** [FeloVilches/Webforge-Express#25]
![console](https://cloud.githubusercontent.com/assets/18412932/16352137/a6443b80-3a41-11e6-928a-7328141f96e2.png)

En la imagen se muestra el error, y no me deja probar ciertas funcionalidades ... Creo que es un problema en el merge

**Comment by fbnr** [comment]
Esta en la rama grupo3_sprint3, ya que no quiero trabajar en la master y ese es nuestra rama para crear funcionalidades

**Comment by Angerback** [comment]
El merge que yo hice fue de la rama grupo3_sprint3 a la master. Es impsible que haya un problema en la rama qie mencionas por el merge, ya que no se tocó. Actualmente en la master funciona el home.
Consejo: toma la master, saca una rama y trabaja ahi lo tuyo por favor.

**Comment by fbnr** [comment]
Lo hice y aún no me funciona. Pensé que era por algún script que había hecho Richard, pero me di cuenta que a otros les funciona y a mi no. Probaré otras cosas, gracias.
