### ISSUE TITLE
No se muestra en heroku controlador evaluaciones

### ISSUE THREAD

**Issue by nelsonjerezv** [FeloVilches/Webforge-Express#6]
se encuentra el script al controlador en index
se encuentra creado el controlador
se encuentra el template con el archivo a mostrar
se encuentra el conotrolador añadido a app.js

de hecho corre localmente como se ve en la segunda imagen

![image](https://cloud.githubusercontent.com/assets/6087535/15466512/6c4f1486-20b0-11e6-82de-23bf3d91053b.png)

![image](https://cloud.githubusercontent.com/assets/6087535/15466577/ae028106-20b0-11e6-938c-0310882ed51d.png)

**Comment by FeloVilches** [comment]
En el estado actual de views/index.ejs no esta incluido el script al controlador de evaluaciones.
Algo asi:
<script src="javascripts/coursesCtrl.js"></script>

**Comment by nelsonjerezv** [comment]
arreglado gracias
